# Generated by Django 4.2.18 on 2025-01-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
