# Generated by Django 4.2.18 on 2025-01-27 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.SmallIntegerField(blank=True)),
                ('free_time_per_week', models.PositiveSmallIntegerField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg_number', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_limit_from', models.IntegerField(blank=True)),
                ('age_limit_to', models.IntegerField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('gender_limit', models.CharField(blank=True, choices=[('M', 'Male'), ('m', 'Male (lowercase)'), ('F', 'Female'), ('f', 'Female (lowercase)')], max_length=1)),
                ('state', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('assigned_benefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charities.benefactor')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charities.charity')),
            ],
        ),
    ]
